CREATE DATABASE IF NOT EXISTS OPENAUTODATA;

CREATE TABLE IF NOT EXISTS OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES (
    RUN_ID STRING,
    ARM STRING,
    CHUNK_ID NUMBER,
    ROUND_NUM NUMBER,
    QUESTION_TYPE STRING,
    CONTEXT STRING,
    QUESTION STRING,
    REFERENCE_ANSWER STRING,
    RUBRIC VARIANT,
    WEAK_ANSWER STRING,
    STRONG_ANSWER STRING,
    WEAK_SCORE FLOAT,
    STRONG_SCORE FLOAT,
    SCORE_GAP FLOAT,
    JUDGE_FEEDBACK STRING,
    STATUS STRING,
    FAILURE_MODE STRING,
    FAIL_REASON STRING,
    RAW VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPENAUTODATA.PUBLIC.OPENAUTODATA_ACCEPTED_SET (
    RUN_ID STRING,
    ARM STRING,
    CHUNK_ID NUMBER,
    ROUND_NUM NUMBER,
    QUESTION_TYPE STRING,
    CONTEXT STRING,
    QUESTION STRING,
    REFERENCE_ANSWER STRING,
    RUBRIC VARIANT,
    WEAK_SCORE FLOAT,
    STRONG_SCORE FLOAT,
    SCORE_GAP FLOAT,
    JUDGE_FEEDBACK STRING,
    STATUS STRING,
    RAW VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES ADD COLUMN IF NOT EXISTS QUESTION_TYPE STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES ADD COLUMN IF NOT EXISTS CONTEXT STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES ADD COLUMN IF NOT EXISTS RUBRIC VARIANT;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES ADD COLUMN IF NOT EXISTS FAILURE_MODE STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES ADD COLUMN IF NOT EXISTS FAIL_REASON STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_ACCEPTED_SET ADD COLUMN IF NOT EXISTS QUESTION_TYPE STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_ACCEPTED_SET ADD COLUMN IF NOT EXISTS CONTEXT STRING;
ALTER TABLE OPENAUTODATA.PUBLIC.OPENAUTODATA_ACCEPTED_SET ADD COLUMN IF NOT EXISTS RUBRIC VARIANT;
