CREATE DATABASE IF NOT EXISTS OPENAUTODATA;

CREATE TABLE IF NOT EXISTS OPENAUTODATA.PUBLIC.OPENAUTODATA_TRAJECTORIES (
    RUN_ID STRING,
    ARM STRING,
    CHUNK_ID NUMBER,
    ROUND_NUM NUMBER,
    QUESTION STRING,
    REFERENCE_ANSWER STRING,
    WEAK_ANSWER STRING,
    STRONG_ANSWER STRING,
    WEAK_SCORE FLOAT,
    STRONG_SCORE FLOAT,
    SCORE_GAP FLOAT,
    JUDGE_FEEDBACK STRING,
    STATUS STRING,
    RAW VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPENAUTODATA.PUBLIC.OPENAUTODATA_ACCEPTED_SET (
    RUN_ID STRING,
    ARM STRING,
    CHUNK_ID NUMBER,
    ROUND_NUM NUMBER,
    QUESTION STRING,
    REFERENCE_ANSWER STRING,
    WEAK_SCORE FLOAT,
    STRONG_SCORE FLOAT,
    SCORE_GAP FLOAT,
    JUDGE_FEEDBACK STRING,
    STATUS STRING,
    RAW VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
